#权重矩阵:[1+厚度,2-氧气获得,3-体力获得]
DATA={'抑制':('弃1张牌,获得2\n点氧气,1点体力','self.oxygen+=2\nself.hp+=1\nself.choose()',[0,0,2]),
'思考者':('消耗2点氧气,抽2\n张牌.被弃时随机\n造成2点伤害','self.oxygen-=2\nself.draw()\nself.draw()','r.choice(sbs).hp-=2',[3,4,2]),
'手枪':('随机造成2点伤害.\n或消耗3点氧气,\n指定造成3点伤害','o=r.choice(sbs)\nif "金属探测器" not in o.cards:o.hp-=2\nelse:o.show("金属探测器")','self.oxygen-=3\nself.objection()','if "金属探测器" not in sbs[self.defendant].cards:sbs[self.defendant].hp-=3\nelse:sbs[self.defendant].show("金属探测器")',[1,2,3.7],[1,5,6],0),
'金属探测器':('抽1张气瓶.在手牌中\n时,不受到手枪伤害','self.draw("气瓶")',[1,1,4]),
'气瓶':('所有人失去1点\n体力.获得2点氧\n气.补充2点氧气','for o in sbs:\n	o.hp-=1\nself.oxygen+=2\nglobal oxygen\noxygen+=2',[1,0,2.7]),
'勾玉':('所有人抽1张心灵枷\n锁.被弃时抽1张牌','for o in sbs:o.draw("心灵枷锁")','self.draw()',[1,2,3]),
'暴风吸入':('消耗1点体力,掠\n夺目标2点氧气','self.hp-=1\nself.objection()','sbs[self.defendant].oxygen-=2\nself.oxygen+=2\nif sbs[self.defendant].oxygen<0:\n	self.oxygen+=sbs[self.defendant].oxygen\n	sbs[self.defendant].oxygen=0',[1,0,4]),
'小百合':('随机复制1张手牌.\n无手牌先抽1张牌','if not self.cards:self.draw()\no=r.randint(0,len(self.cards)-1)\nself.draw(self.cards[o])\nself.card[-1].skill=self.card[o].skill\nself.card[-1].discribe.text=self.card[o].discribe.text',[2,2,3]),
'导弹':('消耗2点氧气,从目\n标手牌中抽1张牌','self.oxygen-=2\nself.objection()','if sbs[self.defendant].cards:self.draw(sbs[self.defendant].abandon(r.choice(sbs[self.defendant].card)))',[2,4,3]),
'葫芦湖水怪':('弃1张牌,其他\n人随机弃1张牌\n或失去2点体力','for o in sbs:\n	if o is self:o.choose()\n	elif len(o.cards):o.abandon(r.choice(o.card))','for o in sbs:\n	if o is self:o.choose()\n	else:o.hp-=2',[1.3,2,3],[0,2,1.7],0),
'律师徽章':('消耗1点氧气或体力,\n抽2张牌,弃1张牌','self.oxygen-=1\nself.draw()\nself.draw()\nself.choose()','self.hp-=1\nself.draw()\nself.draw()\nself.choose()',[2,3,3],[2,2,4],0),
'检察官徽章':('失去2点体力,造成\n3点伤害,抽1张牌','self.hp-=2\nself.objection()','sbs[self.defendant].hp-=3\nself.draw()',[2,2,3.5]),
'钓竿':('消耗1点氧气,你\n和目标各抽2张牌','self.oxygen-=1\nself.objection()','for o in range(2):\n	self.draw()\n	sbs[self.defendant].draw()',[2.5,3,3]),
'大将军长枪':('消耗6点氧气,造\n成4点伤害.友方\n回合受到伤害\n时获得-2消耗','self.oxygen-=6\nself.objection()','sbs[self.defendant].hp-=4',[1,8,1.7]),
'小刀':('消耗2点氧气,造\n成2点伤害,手牌\n中小刀-1消耗','self.oxygen-=2\nself.objection()','sbs[self.defendant].hp-=2\nif "小刀" in self.cards:\n	self.show("小刀")\n	for o in range(len(self.cards)):\n		if self.cards[o]=="小刀" and self.card[o].skill[-1][1]!=2:\n			self.card[o].skill[0]=self.card[o].skill[0][:2]+str(int(self.card[o].skill[0][2])-1)+self.card[o].skill[0][3:]\n			self.card[o].discribe.text=self.card[o].skill[0]\n			self.card[o].skill[1]=self.card[o].skill[1][:13]+self.card[o].skill[0][2]+self.card[o].skill[1][14:]\n			self.card[o].skill[-1]=[self.card[o].skill[-1][0],self.card[o].skill[-1][1]-1,self.card[o].skill[-1][2]]',[1,4,2.3]),
'相机':('若体力不高\n于5,消耗1点氧\n气,获得3点体力','if self.hp<=5:\n	self.oxygen-=1\n	self.hp+=3',[1,3,0]),
'复仇':('消耗2点氧气,造成双\n方手牌数差的伤害','self.oxygen-=2\nself.objection()','sbs[self.defendant].hp-=abs(len(self.cards)-len(sbs[self.defendant].cards))',[1,4,2.2]),
'拉炮':('造成1点伤害,目\n标随机弃1张牌','self.objection()','sbs[self.defendant].hp-=1\nif sbs[self.defendant].cards:sbs[self.defendant].abandon(r.choice(sbs[self.defendant].card))',[1.3,2,3.3]),
'仓院之壶':('消耗1点体力,\n抽1张抉择和挣\n扎,结束回合','self.hp-=1\nself.draw("抉择")\nself.draw("挣扎")\nClock.schedule_once(self.endturn)',[2.5,1.5,4]),
'尸检报告':('弃置所有手牌,\n抽取等量卡牌','i=len(self.cards)\nfor o in range(i):self.abandon(self.card[0])\nfor o in range(i):self.draw()',[0,2,3]),
'心灵枷锁':('失去1点氧气或体力','self.oxygen-=1','self.hp-=1',[1,3,3],[1,2,4],0),
'抉择':('吸入2点氧气\n(%d)或抽1张牌','self.breathe(2)','self.draw()',[1,0,3],[2,2,3],0),
'挣扎':('抽1张牌','self.draw()',[2,2,3])}