name: DL6-OxygenFight

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev

      - name: Use Buildozer GitHub Action
        uses: ArturSpirin/buildozer-action@v1
        with:
          command: "buildozer -v android debug"
          buildozer-version: "stable"
          python-version: "3.11"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: bin/*.apk
