name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: artem-sheremet/buildozer-action@v0.2
      with:
        buildozer-version: stable
        target: android
        type: debug

    - uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/
