name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-8-jdk \
            python3-pip \
            python3-venv \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            ninja-build \
            curl

    - name: Set up Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

    - name: Fix libtool issues
      run: |
        sudo apt-get remove -y libtool libtool-bin
        sudo apt-get install -y libtool libtool-bin
        libtool --version
        mkdir -p m4
        libtoolize --force --copy

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.19
        pip install virtualenv
        pip install kivy==2.2.1
        pip install plyer

    - name: Build with Buildozer
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export LIBTOOLIZE=libtoolize
        export ACLOCAL=aclocal
        export AUTOMAKE=automake
        export AUTOHEADER=autoheader
        export AUTOCONF=autoconf
        buildozer android clean
        buildozer -v android debug
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk
        ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: bin/*.apk
