name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git zip unzip openjdk-8-jdk \
            python3-pip autoconf automake libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            libncursesw5-dev cmake libffi-dev libssl-dev \
            curl wget

    - name: Install Buildozer with specific version
      run: |
        pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install cython==0.29.33
        pip install kivy==2.2.1

    - name: Pre-setup Buildozer environment
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        
        # 创建必要的目录结构
        mkdir -p ~/.buildozer/android/platform
        
        # 手动设置 python-for-android
        git clone https://github.com/kivy/python-for-android ~/.buildozer/android/platform/python-for-android
        cd ~/.buildozer/android/platform/python-for-android
        git checkout 2023.08.04  # 使用稳定版本
        
        # 安装 python-for-android 依赖
        pip install -r requirements.txt

    - name: Initialize Buildozer
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        
        # 初始化 buildozer.spec
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # 确保接受许可证
        if ! grep -q "android.accept_sdk_license" buildozer.spec; then
          echo "android.accept_sdk_license = True" >> buildozer.spec
        fi
        
        # 设置使用本地 python-for-android
        if ! grep -q "p4a.source_dir" buildozer.spec; then
          echo "p4a.source_dir = $HOME/.buildozer/android/platform/python-for-android" >> buildozer.spec
        fi

    - name: Build APK
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        
        # 构建 APK
        buildozer android clean
        buildozer -v android debug
      timeout-minutes: 30

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk
