name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build APK
      uses: kivy/buildozer-action@master
      with:
        work-dir: .
        buildozer-version: stable

    - uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
