name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository --yes universe
        sudo add-apt-repository --yes multiverse
        sudo add-apt-repository --yes restricted
        sudo apt-get update
        apt-cache search libtinfo | head -5 || echo "No libtinfo packages found"
        apt-cache search ncurses | grep tinfo | head -5 || echo "No tinfo-related packages found"
        sudo apt-get install -y \
            zip \
            unzip \
            openjdk-8-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            automake
        sudo apt-get install -y libtinfo5 || \
        sudo apt-get install -y libtinfo-dev || \
        sudo apt-get install -y ncurses-term || \
        echo "Optional terminal packages not available, continuing anyway"

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.19
        pip install virtualenv

    - name: Build with Buildozer
      run: |
        buildozer -v android debug
      env:
        PATH: "/home/runner/.local/bin:$PATH"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: bin/*.apk
