name: Build Kivy Android APK

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git zip unzip openjdk-8-jdk \
            python3-pip autoconf automake libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            libncursesw5-dev cmake libffi-dev libssl-dev libltdl7-dev

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33 kivy==2.2.1 plyer

    - name: Fix jnius compatibility issue
      run: |
        find . -name "jnius_utils.pxi" -exec sed -i 's/isinstance(arg, long)/isinstance(arg, int)/g' {} \; 2>/dev/null || true
        find . -name "*.pyx" -exec sed -i 's/isinstance(\(.*\), long)/isinstance(\1, int)/g' {} \; 2>/dev/null || true

    - name: Build APK with specific p4a version
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        pip install --user python-for-android==2023.9.16
        if ! grep -q "android.accept_sdk_license" buildozer.spec; then
          echo "android.accept_sdk_license = True" >> buildozer.spec
        fi
        rm -rf .buildozer
        
        buildozer -v android debug
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}
      timeout-minutes: 40

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk
        retention-days: 7
